import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="size-full" suppressHydrationWarning>
      <body className="flex justify-center items-center min-h-full bg-gray-100">
        {children}
      </body>
    </html>
  );
}
