import type {Metadata} from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className='size-full'>
			<body className='flex justify-around items-center h-screen w-screen bg-gray-100'>
				{children}
			</body>
		</html>
	);
}
